//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Photo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Оборудование CustomAttributes)

    // *** End programmer edit section *** (Оборудование CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОборудованиеE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'"})]
    public class Оборудование : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private IIS.Photo.Фотокиоск fФотокиоск;
        
        // *** Start programmer edit section *** (Оборудование CustomMembers)

        // *** End programmer edit section *** (Оборудование CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ID CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ID Get start)

                // *** End programmer edit section *** (Оборудование.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Оборудование.ID Get end)

                // *** End programmer edit section *** (Оборудование.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ID Set start)

                // *** End programmer edit section *** (Оборудование.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Оборудование.ID Set end)

                // *** End programmer edit section *** (Оборудование.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Наименование CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Наименование Get start)

                // *** End programmer edit section *** (Оборудование.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Оборудование.Наименование Get end)

                // *** End programmer edit section *** (Оборудование.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Наименование Set start)

                // *** End programmer edit section *** (Оборудование.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Оборудование.Наименование Set end)

                // *** End programmer edit section *** (Оборудование.Наименование Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Photo.Фотокиоск.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Фотокиоск CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Фотокиоск CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Фотокиоск"})]
        public virtual IIS.Photo.Фотокиоск Фотокиоск
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Фотокиоск Get start)

                // *** End programmer edit section *** (Оборудование.Фотокиоск Get start)
                IIS.Photo.Фотокиоск result = this.fФотокиоск;
                // *** Start programmer edit section *** (Оборудование.Фотокиоск Get end)

                // *** End programmer edit section *** (Оборудование.Фотокиоск Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Фотокиоск Set start)

                // *** End programmer edit section *** (Оборудование.Фотокиоск Set start)
                this.fФотокиоск = value;
                // *** Start programmer edit section *** (Оборудование.Фотокиоск Set end)

                // *** End programmer edit section *** (Оборудование.Фотокиоск Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОборудованиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеE", typeof(IIS.Photo.Оборудование));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)
    public class DetailArrayOfОборудование : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Photo.DetailArrayOfОборудование members)

        // *** End programmer edit section *** (IIS.Photo.DetailArrayOfОборудование members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Оборудование by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Оборудование.
        /// </summary>
        public DetailArrayOfОборудование(IIS.Photo.Фотокиоск fФотокиоск) : 
                base(typeof(Оборудование), ((ICSSoft.STORMNET.DataObject)(fФотокиоск)))
        {
        }
        
        public IIS.Photo.Оборудование this[int index]
        {
            get
            {
                return ((IIS.Photo.Оборудование)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Photo.Оборудование dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
