//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Photo
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплаты.
    /// </summary>
    // *** Start programmer edit section *** (Оплаты CustomAttributes)

    // *** End programmer edit section *** (Оплаты CustomAttributes)
    public enum Оплаты
    {
        
        // *** Start programmer edit section *** (Оплаты.Безналичный CustomAttributes)

        // *** End programmer edit section *** (Оплаты.Безналичный CustomAttributes)
        Безналичный,
        
        // *** Start programmer edit section *** (Оплаты.Наличный CustomAttributes)

        // *** End programmer edit section *** (Оплаты.Наличный CustomAttributes)
        Наличный,
        
        // *** Start programmer edit section *** (Оплаты.СПБ CustomAttributes)

        // *** End programmer edit section *** (Оплаты.СПБ CustomAttributes)
        СПБ,
    }
}
