//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Photo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплата.
    /// </summary>
    // *** Start programmer edit section *** (Оплата CustomAttributes)

    // *** End programmer edit section *** (Оплата CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОплатаE", new string[] {
            "ТипОплаты as \'Тип оплаты\'",
            "Сумма as \'Сумма\'",
            "Номер as \'Номер\'"})]
    [AssociatedDetailViewAttribute("ОплатаE", "Фото", "ФотоE", true, "", "Фото", true, new string[] {
            ""})]
    [View("ОплатаL", new string[] {
            "ТипОплаты as \'Тип оплаты\'",
            "Сумма as \'Сумма\'",
            "Номер as \'Номер\'"})]
    public class Оплата : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Photo.Оплаты fТипОплаты;
        
        private double fСумма;
        
        private IIS.Photo.Клиент fКлиент;
        
        private IIS.Photo.DetailArrayOfФото fФото;
        
        // *** Start programmer edit section *** (Оплата CustomMembers)

        // *** End programmer edit section *** (Оплата CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Номер CustomAttributes)

        // *** End programmer edit section *** (Оплата.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Номер Get start)

                // *** End programmer edit section *** (Оплата.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Оплата.Номер Get end)

                // *** End programmer edit section *** (Оплата.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Номер Set start)

                // *** End programmer edit section *** (Оплата.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Оплата.Номер Set end)

                // *** End programmer edit section *** (Оплата.Номер Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Сумма CustomAttributes)

        // *** End programmer edit section *** (Оплата.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Сумма Get start)

                // *** End programmer edit section *** (Оплата.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Оплата.Сумма Get end)

                // *** End programmer edit section *** (Оплата.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Сумма Set start)

                // *** End programmer edit section *** (Оплата.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Оплата.Сумма Set end)

                // *** End programmer edit section *** (Оплата.Сумма Set end)
            }
        }
        
        /// <summary>
        /// ТипОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ТипОплаты CustomAttributes)

        // *** End programmer edit section *** (Оплата.ТипОплаты CustomAttributes)
        public virtual IIS.Photo.Оплаты ТипОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ТипОплаты Get start)

                // *** End programmer edit section *** (Оплата.ТипОплаты Get start)
                IIS.Photo.Оплаты result = this.fТипОплаты;
                // *** Start programmer edit section *** (Оплата.ТипОплаты Get end)

                // *** End programmer edit section *** (Оплата.ТипОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ТипОплаты Set start)

                // *** End programmer edit section *** (Оплата.ТипОплаты Set start)
                this.fТипОплаты = value;
                // *** Start programmer edit section *** (Оплата.ТипОплаты Set end)

                // *** End programmer edit section *** (Оплата.ТипОплаты Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Клиент CustomAttributes)

        // *** End programmer edit section *** (Оплата.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Photo.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Клиент Get start)

                // *** End programmer edit section *** (Оплата.Клиент Get start)
                IIS.Photo.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Оплата.Клиент Get end)

                // *** End programmer edit section *** (Оплата.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Клиент Set start)

                // *** End programmer edit section *** (Оплата.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Оплата.Клиент Set end)

                // *** End programmer edit section *** (Оплата.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Фото CustomAttributes)

        // *** End programmer edit section *** (Оплата.Фото CustomAttributes)
        public virtual IIS.Photo.DetailArrayOfФото Фото
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Фото Get start)

                // *** End programmer edit section *** (Оплата.Фото Get start)
                if ((this.fФото == null))
                {
                    this.fФото = new IIS.Photo.DetailArrayOfФото(this);
                }
                IIS.Photo.DetailArrayOfФото result = this.fФото;
                // *** Start programmer edit section *** (Оплата.Фото Get end)

                // *** End programmer edit section *** (Оплата.Фото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Фото Set start)

                // *** End programmer edit section *** (Оплата.Фото Set start)
                this.fФото = value;
                // *** Start programmer edit section *** (Оплата.Фото Set end)

                // *** End programmer edit section *** (Оплата.Фото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОплатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаE", typeof(IIS.Photo.Оплата));
                }
            }
            
            /// <summary>
            /// "ОплатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаL", typeof(IIS.Photo.Оплата));
                }
            }
        }
    }
}
