//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Photo
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Режимы.
    /// </summary>
    // *** Start programmer edit section *** (Режимы CustomAttributes)

    // *** End programmer edit section *** (Режимы CustomAttributes)
    public enum Режимы
    {
        
        // *** Start programmer edit section *** (Режимы.Цветная CustomAttributes)

        // *** End programmer edit section *** (Режимы.Цветная CustomAttributes)
        Цветная,
        
        // *** Start programmer edit section *** (Режимы.ЧБ CustomAttributes)

        // *** End programmer edit section *** (Режимы.ЧБ CustomAttributes)
        ЧБ,
    }
}
