//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Photo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Фото.
    /// </summary>
    // *** Start programmer edit section *** (Фото CustomAttributes)

    // *** End programmer edit section *** (Фото CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФотоE", new string[] {
            "Режим as \'Режим\'",
            "Длина as \'Длина\'",
            "Ширина as \'Ширина\'",
            "Номер as \'Номер\'"})]
    public class Фото : ICSSoft.STORMNET.DataObject
    {
        
        private int fДлина;
        
        private int fШирина;
        
        private int fНомер;
        
        private IIS.Photo.Режимы fРежим;
        
        private IIS.Photo.Оплата fОплата;
        
        // *** Start programmer edit section *** (Фото CustomMembers)

        // *** End programmer edit section *** (Фото CustomMembers)

        
        /// <summary>
        /// Длина.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Длина CustomAttributes)

        // *** End programmer edit section *** (Фото.Длина CustomAttributes)
        public virtual int Длина
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Длина Get start)

                // *** End programmer edit section *** (Фото.Длина Get start)
                int result = this.fДлина;
                // *** Start programmer edit section *** (Фото.Длина Get end)

                // *** End programmer edit section *** (Фото.Длина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Длина Set start)

                // *** End programmer edit section *** (Фото.Длина Set start)
                this.fДлина = value;
                // *** Start programmer edit section *** (Фото.Длина Set end)

                // *** End programmer edit section *** (Фото.Длина Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Номер CustomAttributes)

        // *** End programmer edit section *** (Фото.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Номер Get start)

                // *** End programmer edit section *** (Фото.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Фото.Номер Get end)

                // *** End programmer edit section *** (Фото.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Номер Set start)

                // *** End programmer edit section *** (Фото.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Фото.Номер Set end)

                // *** End programmer edit section *** (Фото.Номер Set end)
            }
        }
        
        /// <summary>
        /// Режим.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Режим CustomAttributes)

        // *** End programmer edit section *** (Фото.Режим CustomAttributes)
        public virtual IIS.Photo.Режимы Режим
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Режим Get start)

                // *** End programmer edit section *** (Фото.Режим Get start)
                IIS.Photo.Режимы result = this.fРежим;
                // *** Start programmer edit section *** (Фото.Режим Get end)

                // *** End programmer edit section *** (Фото.Режим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Режим Set start)

                // *** End programmer edit section *** (Фото.Режим Set start)
                this.fРежим = value;
                // *** Start programmer edit section *** (Фото.Режим Set end)

                // *** End programmer edit section *** (Фото.Режим Set end)
            }
        }
        
        /// <summary>
        /// Ширина.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Ширина CustomAttributes)

        // *** End programmer edit section *** (Фото.Ширина CustomAttributes)
        public virtual int Ширина
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Ширина Get start)

                // *** End programmer edit section *** (Фото.Ширина Get start)
                int result = this.fШирина;
                // *** Start programmer edit section *** (Фото.Ширина Get end)

                // *** End programmer edit section *** (Фото.Ширина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Ширина Set start)

                // *** End programmer edit section *** (Фото.Ширина Set start)
                this.fШирина = value;
                // *** Start programmer edit section *** (Фото.Ширина Set end)

                // *** End programmer edit section *** (Фото.Ширина Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Photo.Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Фото.Оплата CustomAttributes)

        // *** End programmer edit section *** (Фото.Оплата CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Оплата"})]
        public virtual IIS.Photo.Оплата Оплата
        {
            get
            {
                // *** Start programmer edit section *** (Фото.Оплата Get start)

                // *** End programmer edit section *** (Фото.Оплата Get start)
                IIS.Photo.Оплата result = this.fОплата;
                // *** Start programmer edit section *** (Фото.Оплата Get end)

                // *** End programmer edit section *** (Фото.Оплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фото.Оплата Set start)

                // *** End programmer edit section *** (Фото.Оплата Set start)
                this.fОплата = value;
                // *** Start programmer edit section *** (Фото.Оплата Set end)

                // *** End programmer edit section *** (Фото.Оплата Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФотоE", typeof(IIS.Photo.Фото));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Фото.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfФото CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfФото CustomAttributes)
    public class DetailArrayOfФото : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Photo.DetailArrayOfФото members)

        // *** End programmer edit section *** (IIS.Photo.DetailArrayOfФото members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Фото by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Фото.
        /// </summary>
        public DetailArrayOfФото(IIS.Photo.Оплата fОплата) : 
                base(typeof(Фото), ((ICSSoft.STORMNET.DataObject)(fОплата)))
        {
        }
        
        public IIS.Photo.Фото this[int index]
        {
            get
            {
                return ((IIS.Photo.Фото)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Photo.Фото dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
