//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Photo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Фотокиоск.
    /// </summary>
    // *** Start programmer edit section *** (Фотокиоск CustomAttributes)

    // *** End programmer edit section *** (Фотокиоск CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФотокиоскE", new string[] {
            "ID as \'ID\'",
            "Адрес as \'Адрес\'",
            "Состояние as \'Состояние\'"})]
    [AssociatedDetailViewAttribute("ФотокиоскE", "Оборудование", "ОборудованиеE", true, "", "Оборудование", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ФотокиоскE", "Чек", "ЧекE", true, "", "Чек", true, new string[] {
            ""})]
    [View("ФотокиоскL", new string[] {
            "ID as \'ID\'",
            "Адрес as \'Адрес\'",
            "Состояние as \'Состояние\'"})]
    public class Фотокиоск : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        private string fСостояние;
        
        private int fID;
        
        private IIS.Photo.DetailArrayOfОборудование fОборудование;
        
        private IIS.Photo.DetailArrayOfЧек fЧек;
        
        // *** Start programmer edit section *** (Фотокиоск CustomMembers)

        // *** End programmer edit section *** (Фотокиоск CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Фотокиоск.ID CustomAttributes)

        // *** End programmer edit section *** (Фотокиоск.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Фотокиоск.ID Get start)

                // *** End programmer edit section *** (Фотокиоск.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Фотокиоск.ID Get end)

                // *** End programmer edit section *** (Фотокиоск.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фотокиоск.ID Set start)

                // *** End programmer edit section *** (Фотокиоск.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Фотокиоск.ID Set end)

                // *** End programmer edit section *** (Фотокиоск.ID Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Фотокиоск.Адрес CustomAttributes)

        // *** End programmer edit section *** (Фотокиоск.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Фотокиоск.Адрес Get start)

                // *** End programmer edit section *** (Фотокиоск.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Фотокиоск.Адрес Get end)

                // *** End programmer edit section *** (Фотокиоск.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фотокиоск.Адрес Set start)

                // *** End programmer edit section *** (Фотокиоск.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Фотокиоск.Адрес Set end)

                // *** End programmer edit section *** (Фотокиоск.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Фотокиоск.Состояние CustomAttributes)

        // *** End programmer edit section *** (Фотокиоск.Состояние CustomAttributes)
        [StrLen(255)]
        public virtual string Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Фотокиоск.Состояние Get start)

                // *** End programmer edit section *** (Фотокиоск.Состояние Get start)
                string result = this.fСостояние;
                // *** Start programmer edit section *** (Фотокиоск.Состояние Get end)

                // *** End programmer edit section *** (Фотокиоск.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фотокиоск.Состояние Set start)

                // *** End programmer edit section *** (Фотокиоск.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Фотокиоск.Состояние Set end)

                // *** End programmer edit section *** (Фотокиоск.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Фотокиоск.
        /// </summary>
        // *** Start programmer edit section *** (Фотокиоск.Оборудование CustomAttributes)

        // *** End programmer edit section *** (Фотокиоск.Оборудование CustomAttributes)
        public virtual IIS.Photo.DetailArrayOfОборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (Фотокиоск.Оборудование Get start)

                // *** End programmer edit section *** (Фотокиоск.Оборудование Get start)
                if ((this.fОборудование == null))
                {
                    this.fОборудование = new IIS.Photo.DetailArrayOfОборудование(this);
                }
                IIS.Photo.DetailArrayOfОборудование result = this.fОборудование;
                // *** Start programmer edit section *** (Фотокиоск.Оборудование Get end)

                // *** End programmer edit section *** (Фотокиоск.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фотокиоск.Оборудование Set start)

                // *** End programmer edit section *** (Фотокиоск.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (Фотокиоск.Оборудование Set end)

                // *** End programmer edit section *** (Фотокиоск.Оборудование Set end)
            }
        }
        
        /// <summary>
        /// Фотокиоск.
        /// </summary>
        // *** Start programmer edit section *** (Фотокиоск.Чек CustomAttributes)

        // *** End programmer edit section *** (Фотокиоск.Чек CustomAttributes)
        public virtual IIS.Photo.DetailArrayOfЧек Чек
        {
            get
            {
                // *** Start programmer edit section *** (Фотокиоск.Чек Get start)

                // *** End programmer edit section *** (Фотокиоск.Чек Get start)
                if ((this.fЧек == null))
                {
                    this.fЧек = new IIS.Photo.DetailArrayOfЧек(this);
                }
                IIS.Photo.DetailArrayOfЧек result = this.fЧек;
                // *** Start programmer edit section *** (Фотокиоск.Чек Get end)

                // *** End programmer edit section *** (Фотокиоск.Чек Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фотокиоск.Чек Set start)

                // *** End programmer edit section *** (Фотокиоск.Чек Set start)
                this.fЧек = value;
                // *** Start programmer edit section *** (Фотокиоск.Чек Set end)

                // *** End programmer edit section *** (Фотокиоск.Чек Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФотокиоскE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФотокиоскE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФотокиоскE", typeof(IIS.Photo.Фотокиоск));
                }
            }
            
            /// <summary>
            /// "ФотокиоскL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФотокиоскL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФотокиоскL", typeof(IIS.Photo.Фотокиоск));
                }
            }
        }
    }
}
