//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Photo
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Чек.
    /// </summary>
    // *** Start programmer edit section *** (Чек CustomAttributes)

    // *** End programmer edit section *** (Чек CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧекE", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'"})]
    public class Чек : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Photo.Оплата fОплата;
        
        private IIS.Photo.Фотокиоск fФотокиоск;
        
        // *** Start programmer edit section *** (Чек CustomMembers)

        // *** End programmer edit section *** (Чек CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Дата CustomAttributes)

        // *** End programmer edit section *** (Чек.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Дата Get start)

                // *** End programmer edit section *** (Чек.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Чек.Дата Get end)

                // *** End programmer edit section *** (Чек.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Дата Set start)

                // *** End programmer edit section *** (Чек.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Чек.Дата Set end)

                // *** End programmer edit section *** (Чек.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Номер CustomAttributes)

        // *** End programmer edit section *** (Чек.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Номер Get start)

                // *** End programmer edit section *** (Чек.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Чек.Номер Get end)

                // *** End programmer edit section *** (Чек.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Номер Set start)

                // *** End programmer edit section *** (Чек.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Чек.Номер Set end)

                // *** End programmer edit section *** (Чек.Номер Set end)
            }
        }
        
        /// <summary>
        /// Чек.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Оплата CustomAttributes)

        // *** End programmer edit section *** (Чек.Оплата CustomAttributes)
        [PropertyStorage(new string[] {
                "Оплата"})]
        [NotNull()]
        public virtual IIS.Photo.Оплата Оплата
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Оплата Get start)

                // *** End programmer edit section *** (Чек.Оплата Get start)
                IIS.Photo.Оплата result = this.fОплата;
                // *** Start programmer edit section *** (Чек.Оплата Get end)

                // *** End programmer edit section *** (Чек.Оплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Оплата Set start)

                // *** End programmer edit section *** (Чек.Оплата Set start)
                this.fОплата = value;
                // *** Start programmer edit section *** (Чек.Оплата Set end)

                // *** End programmer edit section *** (Чек.Оплата Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Photo.Фотокиоск.
        /// </summary>
        // *** Start programmer edit section *** (Чек.Фотокиоск CustomAttributes)

        // *** End programmer edit section *** (Чек.Фотокиоск CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Фотокиоск"})]
        public virtual IIS.Photo.Фотокиоск Фотокиоск
        {
            get
            {
                // *** Start programmer edit section *** (Чек.Фотокиоск Get start)

                // *** End programmer edit section *** (Чек.Фотокиоск Get start)
                IIS.Photo.Фотокиоск result = this.fФотокиоск;
                // *** Start programmer edit section *** (Чек.Фотокиоск Get end)

                // *** End programmer edit section *** (Чек.Фотокиоск Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чек.Фотокиоск Set start)

                // *** End programmer edit section *** (Чек.Фотокиоск Set start)
                this.fФотокиоск = value;
                // *** Start programmer edit section *** (Чек.Фотокиоск Set end)

                // *** End programmer edit section *** (Чек.Фотокиоск Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧекE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧекE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧекE", typeof(IIS.Photo.Чек));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Чек.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЧек CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЧек CustomAttributes)
    public class DetailArrayOfЧек : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Photo.DetailArrayOfЧек members)

        // *** End programmer edit section *** (IIS.Photo.DetailArrayOfЧек members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Чек by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Чек.
        /// </summary>
        public DetailArrayOfЧек(IIS.Photo.Фотокиоск fФотокиоск) : 
                base(typeof(Чек), ((ICSSoft.STORMNET.DataObject)(fФотокиоск)))
        {
        }
        
        public IIS.Photo.Чек this[int index]
        {
            get
            {
                return ((IIS.Photo.Чек)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Photo.Чек dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
