




CREATE TABLE Оборудование (
 primaryKey UUID NOT NULL,
 ID INT NULL,
 Наименование VARCHAR(255) NULL,
 Фотокиоск UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Чек (
 primaryKey UUID NOT NULL,
 Дата TIMESTAMP(3) NULL,
 Номер INT NULL,
 Оплата UUID NOT NULL,
 Фотокиоск UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Клиент (
 primaryKey UUID NOT NULL,
 ID INT NULL,
 Email VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Фотокиоск (
 primaryKey UUID NOT NULL,
 Адрес VARCHAR(255) NULL,
 Состояние VARCHAR(255) NULL,
 ID INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Оплата (
 primaryKey UUID NOT NULL,
 Номер INT NULL,
 ТипОплаты VARCHAR(11) NULL,
 Сумма DOUBLE PRECISION NULL,
 Клиент UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Фото (
 primaryKey UUID NOT NULL,
 Длина INT NULL,
 Ширина INT NULL,
 Номер INT NULL,
 Режим VARCHAR(7) NULL,
 Оплата UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Оборудование ADD CONSTRAINT FK23b33eefecd01fc49d103f52c2d41e67e08ebfb4 FOREIGN KEY (Фотокиоск) REFERENCES Фотокиоск; 
CREATE INDEX Index23b33eefecd01fc49d103f52c2d41e67e08ebfb4 on Оборудование (Фотокиоск); 

 ALTER TABLE Чек ADD CONSTRAINT FKbf4ec334b6939b23452764cb3fdc2488d0d005e5 FOREIGN KEY (Оплата) REFERENCES Оплата; 
CREATE INDEX Indexbf4ec334b6939b23452764cb3fdc2488d0d005e5 on Чек (Оплата); 

 ALTER TABLE Чек ADD CONSTRAINT FKe3afe5495ea2d5b98b353f5ab7f4fb5f44838088 FOREIGN KEY (Фотокиоск) REFERENCES Фотокиоск; 
CREATE INDEX Indexe3afe5495ea2d5b98b353f5ab7f4fb5f44838088 on Чек (Фотокиоск); 

 ALTER TABLE Оплата ADD CONSTRAINT FK96a0e5668d03be0948af817953ed1a3d12fd6d26 FOREIGN KEY (Клиент) REFERENCES Клиент; 
CREATE INDEX Index96a0e5668d03be0948af817953ed1a3d12fd6d26 on Оплата (Клиент); 

 ALTER TABLE Фото ADD CONSTRAINT FK5dbf657a9eb131c7a31a7450c7de6790a45c0c1c FOREIGN KEY (Оплата) REFERENCES Оплата; 
CREATE INDEX Index5dbf657a9eb131c7a31a7450c7de6790a45c0c1c on Фото (Оплата); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

